//! Graph agent — translates natural language queries to KQL strings.
//!
//! Uses pattern matching for common query types and LLM for complex ones.
//! The generated KQL strings can be parsed by the ku-kql crate's parser.

use ku_ai::traits::ModelBackend;
use ku_ai::types::{ChatMessage, InferenceOptions};

/// A KQL query result.
#[derive(Debug, Clone)]
pub struct KqlResult {
    /// Generated KQL string.
    pub kql: String,
    /// Whether it was generated by pattern or LLM.
    pub source: KqlSource,
}

/// How the KQL was generated.
#[derive(Debug, Clone, PartialEq)]
pub enum KqlSource {
    /// Generated via pattern matching.
    Pattern,
    /// Generated via LLM.
    Llm,
}

/// Translates natural language queries to KQL.
pub struct GraphAgent {
    max_iterations: usize,
}

impl GraphAgent {
    pub fn new() -> Self {
        Self { max_iterations: 3 }
    }

    /// Translate natural language to KQL using pattern matching.
    ///
    /// Returns `None` if no pattern matches.
    pub fn translate_to_kql(&self, nl_query: &str) -> Option<KqlResult> {
        let lower = nl_query.to_lowercase();

        // Pattern 1: "What do I know about X?" / "What is X?"
        if lower.starts_with("what do i know about") || lower.starts_with("what is") {
            let topic = nl_query
                .split_whitespace()
                .skip(5)
                .collect::<Vec<_>>()
                .join(" ");
            if !topic.is_empty() {
                let topic_clean = topic.trim_end_matches('?').trim();
                return Some(KqlResult {
                    kql: format!(
                        "FIND (k:KU) WHERE k.title CONTAINS \"{}\" LIMIT 20",
                        topic_clean
                    ),
                    source: KqlSource::Pattern,
                });
            }
        }

        // Pattern 2: "How does X relate to Y?"
        if lower.contains("relate to") || lower.contains("connected to") {
            let parts: Vec<&str> = nl_query.splitn(2, "relate to").collect();
            if parts.len() == 2 {
                let a = parts[0]
                    .trim()
                    .trim_start_matches("how does ")
                    .trim_start_matches("How does ")
                    .trim();
                let b = parts[1].trim().trim_end_matches('?').trim();
                return Some(KqlResult {
                    kql: format!(
                        "FIND (a:KU)-[r]->(b:KU) WHERE a.title CONTAINS \"{}\" AND b.title CONTAINS \"{}\" LIMIT 10",
                        a, b
                    ),
                    source: KqlSource::Pattern,
                });
            }
        }

        // Pattern 3: "Show me recent knowledge"
        if lower.contains("recent") {
            return Some(KqlResult {
                kql: "FIND (k:KU) ORDER BY k.created_at DESC LIMIT 20".to_string(),
                source: KqlSource::Pattern,
            });
        }

        // No pattern match
        None
    }

    /// Translate using LLM (for complex queries).
    pub async fn translate_with_llm(
        &self,
        nl_query: &str,
        backend: &dyn ModelBackend,
    ) -> Result<KqlResult, crate::error::MediatorError> {
        let messages = vec![
            ChatMessage::system(
                "You are a KQL (Knowledge Query Language) generator. \
                 Convert the user's natural language question into a KQL query. \
                 KQL syntax: FIND (<alias>:<label>) WHERE <conditions> ORDER BY <field> LIMIT <n>. \
                 Conditions use: <alias>.<field> = \"value\" for exact match, \
                 <alias>.<field> CONTAINS \"value\" for substring search. \
                 Relationship queries: FIND (a:KU)-[r]->(b:KU) WHERE <conditions>. \
                 Available fields: title, gene_type, created_at. \
                 Respond with ONLY the KQL query, nothing else.",
            ),
            ChatMessage::user(nl_query),
        ];

        let options = InferenceOptions {
            temperature: 0.0,
            ..Default::default()
        };
        let response = backend
            .chat(&messages, &options)
            .await
            .map_err(|e| crate::error::MediatorError::GraphQueryError(e.to_string()))?;

        Ok(KqlResult {
            kql: response.content.trim().to_string(),
            source: KqlSource::Llm,
        })
    }

    /// Get the maximum iterations for iterative query refinement.
    pub fn max_iterations(&self) -> usize {
        self.max_iterations
    }
}

impl Default for GraphAgent {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn agent() -> GraphAgent {
        GraphAgent::new()
    }

    #[test]
    fn test_what_do_i_know_about() {
        let a = agent();
        let result = a
            .translate_to_kql("What do I know about quantum physics?")
            .unwrap();
        assert!(result.kql.contains("CONTAINS"));
        assert!(result.kql.contains("quantum physics"));
        assert_eq!(result.source, KqlSource::Pattern);
    }

    #[test]
    fn test_what_is() {
        let a = agent();
        let result = a.translate_to_kql("What is the speed of light?");
        assert!(result.is_some());
    }

    #[test]
    fn test_relate_to() {
        let a = agent();
        let result = a
            .translate_to_kql("How does photosynthesis relate to respiration?")
            .unwrap();
        assert!(result.kql.contains("photosynthesis"));
        assert!(result.kql.contains("respiration"));
        assert_eq!(result.source, KqlSource::Pattern);
    }

    #[test]
    fn test_recent() {
        let a = agent();
        let result = a.translate_to_kql("Show me recent knowledge").unwrap();
        assert!(result.kql.contains("ORDER BY"));
        assert!(result.kql.contains("DESC"));
    }

    #[test]
    fn test_no_pattern_match() {
        let a = agent();
        let result = a.translate_to_kql("Something totally unstructured");
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn test_translate_with_llm() {
        let a = agent();
        let mock = ku_ai::MockBackend::new()
            .with_chat_response("FIND (k:KU) WHERE k.topic = \"AI\" LIMIT 10");
        let result = a
            .translate_with_llm("Show me everything about AI", &mock)
            .await
            .unwrap();
        assert!(result.kql.contains("FIND"));
        assert_eq!(result.source, KqlSource::Llm);
    }
}
