//! # Encoding Verifier — 2-Phase Verification for Encoding Consensus
//!
//! Provides tools to verify that a CoreDna encoding correctly represents
//! the original raw text knowledge.
//!
//! ## Phase A: AI Decomposition Verification
//! Compares two AI-generated CoreDna encodings for semantic agreement:
//! - Same gene_type?
//! - Similar opcodes/instruction types?
//! - Overlapping concept IDs?
//!
//! ## Phase B: Tool Encoding Verification
//! Checks that the binary encode/decode pipeline works correctly:
//! - Round-trip: encode → decode → should match original
//! - CRC integrity
//! - CID computation consistency

use crate::core_dna::{CoreDna, Instruction, encode_core_dna, decode_core_dna};
use crate::types::ConceptId;
use std::collections::HashSet;

// ═══════════════════════════════════════════════════════════════════════════
// Phase A: Decomposition Verification
// ═══════════════════════════════════════════════════════════════════════════

/// Result of an AI's decomposition of raw text into structured instructions.
#[derive(Debug, Clone)]
pub struct DecompositionResult {
    /// Gene type chosen by this AI.
    pub gene_type: u8,

    /// Instructions generated by this AI.
    pub instructions: Vec<Instruction>,

    /// All concept IDs referenced.
    pub concept_ids: Vec<ConceptId>,

    /// AI's self-reported confidence (0.0-1.0).
    pub confidence: f32,
}

impl DecompositionResult {
    /// Extract from a CoreDna.
    pub fn from_core_dna(dna: &CoreDna) -> Self {
        let concept_ids = extract_concept_ids(&dna.instructions);
        Self {
            gene_type: dna.header.gene_type,
            instructions: dna.instructions.clone(),
            concept_ids,
            confidence: 1.0, // Default: full confidence
        }
    }
}

/// Compute semantic agreement between two decomposition results.
///
/// Returns a score in [0.0, 1.0]:
/// - 0.3 weight: gene_type match
/// - 0.3 weight: opcode type overlap (Jaccard similarity)
/// - 0.4 weight: concept ID overlap (Jaccard similarity)
pub fn decomposition_agreement(a: &DecompositionResult, b: &DecompositionResult) -> f32 {
    let mut score = 0.0;

    // Factor 1: Gene type match (0.3)
    if a.gene_type == b.gene_type {
        score += 0.3;
    }

    // Factor 2: Opcode type overlap (0.3)
    let opcodes_a: HashSet<u8> = a.instructions.iter()
        .map(|i| instruction_opcode(i))
        .collect();
    let opcodes_b: HashSet<u8> = b.instructions.iter()
        .map(|i| instruction_opcode(i))
        .collect();
    let opcode_sim = jaccard_similarity(&opcodes_a, &opcodes_b);
    score += 0.3 * opcode_sim;

    // Factor 3: Concept ID overlap (0.4)
    let concepts_a: HashSet<ConceptId> = a.concept_ids.iter().copied().collect();
    let concepts_b: HashSet<ConceptId> = b.concept_ids.iter().copied().collect();
    let concept_sim = jaccard_u64_similarity(&concepts_a, &concepts_b);
    score += 0.4 * concept_sim;

    score
}

/// Compute agreement between two CoreDna directly.
pub fn core_dna_agreement(a: &CoreDna, b: &CoreDna) -> f32 {
    let da = DecompositionResult::from_core_dna(a);
    let db = DecompositionResult::from_core_dna(b);
    decomposition_agreement(&da, &db)
}

// ═══════════════════════════════════════════════════════════════════════════
// Phase B: Tool Encoding Verification
// ═══════════════════════════════════════════════════════════════════════════

/// Result of tool encoding verification.
#[derive(Debug, Clone, PartialEq)]
pub enum ToolVerifyResult {
    /// Encoding round-trip passed — binary is correct.
    Pass,
    /// Round-trip failed — the tool may be tampered with.
    Fail(String),
}

/// Verify that a CoreDna can be correctly encoded and decoded (round-trip).
///
/// This checks that the binary serialization pipeline is not corrupted:
/// 1. Encode CoreDna → bytes
/// 2. Decode bytes → CoreDna'
/// 3. Verify CoreDna' == CoreDna (structurally identical)
///
/// If this fails, the encoding tool itself may be tampered with.
pub fn tool_encoding_check(dna: &CoreDna) -> ToolVerifyResult {
    // Step 1: Encode
    let encoded = match encode_core_dna(dna) {
        Ok(bytes) => bytes,
        Err(e) => return ToolVerifyResult::Fail(format!("Encode failed: {}", e)),
    };

    // Step 2: Decode
    let decoded = match decode_core_dna(&encoded) {
        Ok(d) => d,
        Err(e) => return ToolVerifyResult::Fail(format!("Decode failed: {}", e)),
    };

    // Step 3: Structural comparison
    if decoded.header != dna.header {
        return ToolVerifyResult::Fail(format!(
            "Header mismatch: gene_type {} vs {}",
            decoded.header.gene_type, dna.header.gene_type
        ));
    }

    if decoded.instructions.len() != dna.instructions.len() {
        return ToolVerifyResult::Fail(format!(
            "Instruction count mismatch: {} vs {}",
            decoded.instructions.len(), dna.instructions.len()
        ));
    }

    if decoded != *dna {
        return ToolVerifyResult::Fail("Instruction content mismatch after round-trip".into());
    }

    ToolVerifyResult::Pass
}

// ═══════════════════════════════════════════════════════════════════════════
// Helper Functions
// ═══════════════════════════════════════════════════════════════════════════

/// Extract all concept IDs from an instruction list.
fn extract_concept_ids(instructions: &[Instruction]) -> Vec<ConceptId> {
    let mut ids = Vec::new();
    for inst in instructions {
        match inst {
            Instruction::Triple { s, p, o } => { ids.push(*s); ids.push(*p); ids.push(*o); },
            Instruction::Quality { s, q } => { ids.push(*s); ids.push(*q); },
            Instruction::Quantity { s, unit, .. } => { ids.push(*s); ids.push(*unit); },
            Instruction::Sequence { items } => ids.extend(items),
            Instruction::PartOf { part, whole } => { ids.push(*part); ids.push(*whole); },
            Instruction::Located { s, location } => { ids.push(*s); ids.push(*location); },
            Instruction::Temporal { s, time } => { ids.push(*s); ids.push(*time); },
            Instruction::Causal { cause, effect } => { ids.push(*cause); ids.push(*effect); },
            Instruction::Simulates { s, model } => { ids.push(*s); ids.push(*model); },
            Instruction::Condition { cond, result } => { ids.push(*cond); ids.push(*result); },
            Instruction::Agent { actor, action } => { ids.push(*actor); ids.push(*action); },
            Instruction::Tool { action, instrument } => { ids.push(*action); ids.push(*instrument); },
            Instruction::Range { s, .. } => { ids.push(*s); },
            Instruction::Tolerance { s, .. } => { ids.push(*s); },
            Instruction::Constraint { source, target, .. } => { ids.push(*source); ids.push(*target); },
            Instruction::EnumVal { s, values } => { ids.push(*s); ids.extend(values); },
            Instruction::Step { action, target, .. } => { ids.push(*action); ids.push(*target); },
            Instruction::Precond { concept } => ids.push(*concept),
            Instruction::Effect { concept } => ids.push(*concept),
            Instruction::Label { key, value } => { ids.push(*key); ids.push(*value); },
            Instruction::Member { label, .. } => { ids.push(*label); },
            // Non-concept instructions
            Instruction::Certainty { .. }
            | Instruction::Difficulty { .. }
            | Instruction::CidRef { .. }
            | Instruction::Affect { .. }
            | Instruction::TextRef { .. }
            | Instruction::Formula { .. }
            | Instruction::Witness { .. }
            | Instruction::MediaRef { .. }
            | Instruction::CompositeHdr { .. }
            | Instruction::End => {},
        }
    }
    ids.sort_unstable();
    ids.dedup();
    ids
}

/// Get the opcode number for an instruction (for similarity comparison).
fn instruction_opcode(inst: &Instruction) -> u8 {
    match inst {
        Instruction::Triple { .. } => 0x00,
        Instruction::Quality { .. } => 0x01,
        Instruction::Quantity { .. } => 0x02,
        Instruction::Sequence { .. } => 0x03,
        Instruction::PartOf { .. } => 0x04,
        Instruction::Located { .. } => 0x05,
        Instruction::Temporal { .. } => 0x06,
        Instruction::Causal { .. } => 0x07,
        Instruction::Simulates { .. } => 0x08,
        Instruction::Condition { .. } => 0x09,
        Instruction::Agent { .. } => 0x0A,
        Instruction::Tool { .. } => 0x0B,
        Instruction::Range { .. } => 0x0C,
        Instruction::Tolerance { .. } => 0x0D,
        Instruction::Constraint { .. } => 0x0E,
        Instruction::EnumVal { .. } => 0x0F,
        Instruction::Certainty { .. } => 0x10,
        Instruction::Difficulty { .. } => 0x11,
        Instruction::CidRef { .. } => 0x12,
        Instruction::Step { .. } => 0x13,
        Instruction::Precond { .. } => 0x14,
        Instruction::Effect { .. } => 0x15,
        Instruction::Affect { .. } => 0x16,
        Instruction::Label { .. } => 0x17,
        Instruction::TextRef { .. } => 0x18,
        Instruction::Formula { .. } => 0x19,
        Instruction::Witness { .. } => 0x1A,
        Instruction::MediaRef { .. } => 0x1B,
        Instruction::CompositeHdr { .. } => 0x1C,
        Instruction::Member { .. } => 0x1D,
        Instruction::End => 0x1E,
    }
}

/// Jaccard similarity between two sets of u8.
fn jaccard_similarity(a: &HashSet<u8>, b: &HashSet<u8>) -> f32 {
    if a.is_empty() && b.is_empty() {
        return 1.0;
    }
    let intersection = a.intersection(b).count();
    let union = a.union(b).count();
    if union == 0 { 1.0 } else { intersection as f32 / union as f32 }
}

/// Jaccard similarity between two sets of u64 (ConceptId).
fn jaccard_u64_similarity(a: &HashSet<u64>, b: &HashSet<u64>) -> f32 {
    if a.is_empty() && b.is_empty() {
        return 1.0;
    }
    let intersection = a.intersection(b).count();
    let union = a.union(b).count();
    if union == 0 { 1.0 } else { intersection as f32 / union as f32 }
}

// ═══════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core_dna::{CoreDna, CoreDnaHeader};

    fn make_fact(instructions: Vec<Instruction>) -> CoreDna {
        CoreDna {
            header: CoreDnaHeader { version: 2, gene_type: 0, has_concept_table: false },
            concept_table: Vec::new(),
            instructions,
        }
    }

    #[test]
    fn test_decomposition_identical() {
        let dna = make_fact(vec![
            Instruction::Triple { s: 1, p: 2, o: 3 },
            Instruction::End,
        ]);
        let a = DecompositionResult::from_core_dna(&dna);
        let b = DecompositionResult::from_core_dna(&dna);
        let score = decomposition_agreement(&a, &b);
        assert!(score > 0.95, "Identical decompositions should score ~1.0, got {}", score);
    }

    #[test]
    fn test_decomposition_different_gene_type() {
        let dna_a = make_fact(vec![Instruction::Triple { s: 1, p: 2, o: 3 }, Instruction::End]);
        let mut dna_b = dna_a.clone();
        dna_b.header.gene_type = 1; // Hypothesis instead of Fact

        let score = core_dna_agreement(&dna_a, &dna_b);
        assert!(score < 0.8, "Different gene types should reduce score, got {}", score);
    }

    #[test]
    fn test_decomposition_partial_overlap() {
        let dna_a = make_fact(vec![
            Instruction::Triple { s: 1, p: 2, o: 3 },
            Instruction::Certainty { level: 9000 },
            Instruction::End,
        ]);
        let dna_b = make_fact(vec![
            Instruction::Triple { s: 1, p: 2, o: 3 },
            Instruction::Quality { s: 1, q: 5 },
            Instruction::End,
        ]);

        let score = core_dna_agreement(&dna_a, &dna_b);
        // Same gene_type (0.3) + partial opcode overlap + partial concept overlap
        assert!(score > 0.3 && score < 1.0, "Partial overlap should be intermediate, got {}", score);
    }

    #[test]
    fn test_tool_encoding_check_pass() {
        let dna = make_fact(vec![
            Instruction::Triple { s: 42, p: 187, o: 91 },
            Instruction::Certainty { level: 9000 },
        ]);
        assert_eq!(tool_encoding_check(&dna), ToolVerifyResult::Pass);
    }

    #[test]
    fn test_extract_concept_ids() {
        let instructions = vec![
            Instruction::Triple { s: 1, p: 2, o: 3 },
            Instruction::Quality { s: 1, q: 5 },
            Instruction::Certainty { level: 9000 }, // No concept IDs
            Instruction::End,
        ];
        let ids = extract_concept_ids(&instructions);
        assert_eq!(ids, vec![1, 2, 3, 5]);
    }

    #[test]
    fn test_jaccard_empty_sets() {
        let a: HashSet<u8> = HashSet::new();
        let b: HashSet<u8> = HashSet::new();
        assert_eq!(jaccard_similarity(&a, &b), 1.0);
    }

    #[test]
    fn test_jaccard_identical() {
        let a: HashSet<u8> = [1, 2, 3].into_iter().collect();
        assert_eq!(jaccard_similarity(&a, &a), 1.0);
    }

    #[test]
    fn test_jaccard_disjoint() {
        let a: HashSet<u8> = [1, 2].into_iter().collect();
        let b: HashSet<u8> = [3, 4].into_iter().collect();
        assert_eq!(jaccard_similarity(&a, &b), 0.0);
    }
}
