/*
 * Generated by cbindgen from onebrain-mobile-bridge.
 * Do not edit this file by hand.
 */


#ifndef ONEBRAIN_MOBILE_BRIDGE_H
#define ONEBRAIN_MOBILE_BRIDGE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Stable ABI revision understood by the current Swift/Kotlin adapters.
 */
#define OB_MOBILE_BRIDGE_ABI_VERSION 7

#define OB_MOBILE_RUNTIME_OK 0

#define OB_MOBILE_RUNTIME_INVALID_PATH 1

#define OB_MOBILE_RUNTIME_CORE_ERROR 2

#define OB_MOBILE_RUNTIME_LOCK_POISONED 3

#define OB_MOBILE_RUNTIME_NOT_OPEN 4

#define OB_MOBILE_RUNTIME_INVALID_SECURITY_MATERIAL 5

#define OB_MOBILE_RUNTIME_INVALID_DRAFT 6

#define OB_MOBILE_RUNTIME_INVALID_ONBOARDING_CURSOR 7

#define OB_MOBILE_RUNTIME_INVALID_SHARE_SPOOL 8

#define OB_MOBILE_RUNTIME_SHARE_SPOOL_NOT_FOUND 9

#define OB_MOBILE_RUNTIME_INVALID_MEDIA_STAGE 10

typedef struct ObMobileRuntimeSnapshot {
  uint32_t status_code;
  uint64_t process_generation;
  uint32_t activation_phase;
  uint32_t active_grant_count;
  uint8_t recovered_unclean_start;
  uint8_t bootstrap_store_opened;
  uint8_t registry_bootstrap_only;
  uint8_t local_kql_fixture_verified;
  uint8_t private_planner_verified;
  uint8_t no_llm_provider;
  uint8_t stale_callback_rejected;
  uint8_t secure_profile_active;
  uint8_t installation_binding_verified;
  uint8_t installation_created;
  uint8_t security_session_unlocked;
  uint8_t private_vault_ready;
  uint8_t identity_domains_separated;
  uint8_t privacy_defaults_fail_safe;
  uint8_t redacted_history_ready;
  uint64_t encrypted_raw_draft_count;
  uint64_t pending_share_spool_count;
  uint64_t staged_verified_media_count;
  uint32_t onboarding_cursor;
} ObMobileRuntimeSnapshot;

typedef struct ObMobileRawDraftReceipt {
  uint32_t status_code;
  uint8_t draft_ref[39];
  uint32_t draft_ref_len;
  uint8_t content_language[36];
  uint32_t content_language_len;
  uint64_t content_bytes;
  uint64_t saved_at_monotonic_ms;
  uint64_t total_drafts;
} ObMobileRawDraftReceipt;

typedef struct ObMobileShareSpoolSummary {
  uint32_t status_code;
  uint8_t spool_ref[39];
  uint32_t spool_ref_len;
  uint8_t mime_type[64];
  uint32_t mime_type_len;
  uint64_t content_bytes;
  uint64_t received_at_monotonic_ms;
} ObMobileShareSpoolSummary;

typedef struct ObMobileMediaStageReceipt {
  uint32_t status_code;
  uint8_t source_ref[40];
  uint32_t source_ref_len;
  uint8_t media_class[16];
  uint32_t media_class_len;
  uint8_t mime_type[128];
  uint32_t mime_type_len;
  uint64_t content_bytes;
  uint8_t blake3_digest[64];
  uint32_t blake3_digest_len;
} ObMobileMediaStageReceipt;

/**
 * Return the stable native-to-Rust ABI revision.
 */
uint32_t ob_mobile_bridge_abi_version(void);

/**
 * Return a process-lifetime, NUL-terminated Rust bridge version.
 *
 * The caller must not free or mutate this pointer.
 */
const char *ob_mobile_bridge_core_version(void);

/**
 * Report whether this bootstrap-only bridge has requested Registry bytes.
 *
 * Registry transfer authority remains disabled until the explicit Init slice.
 */
uint8_t ob_mobile_bridge_registry_request_issued(void);

/**
 * Bounded deterministic call used to verify the complete generated call path.
 */
uint64_t ob_mobile_bridge_round_trip(uint64_t nonce);

/**
 * Open the process-wide mobile runtime from a native-owned UTF-8 data root.
 *
 * Repeated calls in the same process return the existing generation.
 *
 * # Safety
 *
 * `path` must reference `path_len` readable bytes for the duration of this
 * call. The bytes must form a non-empty UTF-8 path.
 */
struct ObMobileRuntimeSnapshot ob_mobile_runtime_open_utf8(const uint8_t *path, size_t path_len);

/**
 * Open the process-wide runtime with native-protected installation material.
 *
 * The native caller must zeroize its temporary plaintext buffer immediately
 * after this function returns. The material never crosses the Dart bridge.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths for the
 * duration of this call.
 */
struct ObMobileRuntimeSnapshot ob_mobile_runtime_open_secure_utf8(const uint8_t *path,
                                                                  size_t path_len,
                                                                  const uint8_t *security_material,
                                                                  size_t security_material_len);

/**
 * Inspect the process-wide runtime without reopening its database.
 */
struct ObMobileRuntimeSnapshot ob_mobile_runtime_snapshot(void);

/**
 * Quiesce the current process generation.
 */
uint32_t ob_mobile_runtime_graceful_stop(void);

/**
 * Lock and zeroize the current private-node session without relying on a
 * lifecycle callback for correctness.
 */
uint32_t ob_mobile_runtime_lock_private_node(void);

/**
 * Persist bounded UTF-8 text as an encrypted `PrivateLocal` raw draft.
 *
 * The returned reference is opaque. No filesystem path, database handle,
 * encryption key or plaintext content is returned.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths for the
 * duration of this call.
 */
struct ObMobileRawDraftReceipt ob_mobile_runtime_save_raw_text_draft_utf8(const uint8_t *content_language,
                                                                          size_t content_language_len,
                                                                          const uint8_t *content_utf8,
                                                                          size_t content_len);

/**
 * Land a bounded native share callback into the encrypted private spool.
 *
 * This native-only entry point is not exposed to Dart. The callback token is
 * used solely for idempotency and the returned spool reference is opaque.
 *
 * # Safety
 *
 * Every pointer must reference its declared readable byte length.
 */
struct ObMobileShareSpoolSummary ob_mobile_runtime_enqueue_shared_text_utf8(const uint8_t *callback_token,
                                                                            size_t callback_token_len,
                                                                            const uint8_t *mime_type,
                                                                            size_t mime_type_len,
                                                                            const uint8_t *content_utf8,
                                                                            size_t content_len);

/**
 * Return one pending encrypted share spool by stable sorted index.
 */
struct ObMobileShareSpoolSummary ob_mobile_runtime_pending_share_spool_at(size_t index);

/**
 * Import a pending `text/plain` spool into an encrypted raw draft.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths.
 */
struct ObMobileRawDraftReceipt ob_mobile_runtime_import_shared_text_utf8(const uint8_t *spool_ref,
                                                                         size_t spool_ref_len,
                                                                         const uint8_t *content_language,
                                                                         size_t content_language_len);

/**
 * Begin a native-owned system-picker stream into encrypted private staging.
 *
 * Neither a provider URI nor filesystem path enters this ABI.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths.
 */
struct ObMobileMediaStageReceipt ob_mobile_runtime_start_media_stage_utf8(const uint8_t *requested_class,
                                                                          size_t requested_class_len,
                                                                          const uint8_t *declared_mime_type,
                                                                          size_t declared_mime_type_len);

/**
 * Append one bounded plaintext chunk; Rust encrypts and commits it before return.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths.
 */
uint32_t ob_mobile_runtime_append_media_stage(const uint8_t *source_ref,
                                              size_t source_ref_len,
                                              const uint8_t *chunk,
                                              size_t chunk_len);

/**
 * Verify the complete encrypted stream and return its opaque source receipt.
 *
 * # Safety
 *
 * `source_ref` must reference its declared readable byte length.
 */
struct ObMobileMediaStageReceipt ob_mobile_runtime_finish_media_stage_utf8(const uint8_t *source_ref,
                                                                           size_t source_ref_len);

/**
 * Mark a non-verified stream interrupted and remove its encrypted partial file.
 *
 * # Safety
 *
 * `source_ref` must reference its declared readable byte length.
 */
uint32_t ob_mobile_runtime_abort_media_stage_utf8(const uint8_t *source_ref, size_t source_ref_len);

/**
 * Persist a bounded onboarding resume cursor in the Rust bootstrap store.
 */
uint32_t ob_mobile_runtime_set_onboarding_cursor(uint32_t cursor_code);

#endif  /* ONEBRAIN_MOBILE_BRIDGE_H */

/* End generated OneBrain Mobile bridge declarations. */
