/*
 * Generated by cbindgen from onebrain-mobile-bridge.
 * Do not edit this file by hand.
 */


#ifndef ONEBRAIN_MOBILE_BRIDGE_H
#define ONEBRAIN_MOBILE_BRIDGE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Stable ABI revision understood by the current Swift/Kotlin adapters.
 */
#define OB_MOBILE_BRIDGE_ABI_VERSION 11

#define OB_MOBILE_RUNTIME_OK 0

#define OB_MOBILE_RUNTIME_INVALID_PATH 1

#define OB_MOBILE_RUNTIME_CORE_ERROR 2

#define OB_MOBILE_RUNTIME_LOCK_POISONED 3

#define OB_MOBILE_RUNTIME_NOT_OPEN 4

#define OB_MOBILE_RUNTIME_INVALID_SECURITY_MATERIAL 5

#define OB_MOBILE_RUNTIME_INVALID_DRAFT 6

#define OB_MOBILE_RUNTIME_INVALID_ONBOARDING_CURSOR 7

#define OB_MOBILE_RUNTIME_INVALID_SHARE_SPOOL 8

#define OB_MOBILE_RUNTIME_SHARE_SPOOL_NOT_FOUND 9

#define OB_MOBILE_RUNTIME_INVALID_MEDIA_STAGE 10

#define OB_MOBILE_RUNTIME_INVALID_REGISTRY_INIT 11

#define OB_MOBILE_RUNTIME_NO_ACTIVE_REGISTRY_TRANSFER 12

#define OB_MOBILE_RUNTIME_INVALID_REGISTRY_CHUNK 13

#define OB_MOBILE_RUNTIME_REGISTRY_CHUNK_SESSION_BUSY 14

#define OB_MOBILE_RUNTIME_NO_ACTIVE_REGISTRY_CHUNK_SESSION 15

typedef struct ObMobileRegistryPlan {
  uint32_t status_code;
  uint8_t operation_id[129];
  uint32_t operation_id_len;
  uint32_t state_code;
  uint8_t channel_id[65];
  uint32_t channel_id_len;
  uint8_t release_id[65];
  uint32_t release_id_len;
  uint8_t manifest_digest[65];
  uint32_t manifest_digest_len;
  uint8_t trust_profile_digest[65];
  uint32_t trust_profile_digest_len;
  uint64_t head_generation;
  uint64_t release_sequence;
  uint64_t publisher_min_additional_free_bytes;
  uint64_t artifact_total_bytes;
  uint64_t target_total_alloc_bytes;
  uint64_t transfer_initial_bytes;
  uint64_t verification_workspace_bytes;
  uint64_t catalog_growth_bytes;
  uint64_t safety_reserve_bytes;
  uint64_t destination_total_usable_bytes;
  uint64_t measured_free_bytes;
  uint64_t initial_required_free_bytes;
  uint8_t admitted;
} ObMobileRegistryPlan;

typedef struct ObMobileRegistryTransferSchedule {
  uint32_t status_code;
  uint8_t transfer_nonce[129];
  uint32_t transfer_nonce_len;
  uint8_t operation_id[129];
  uint32_t operation_id_len;
  uint8_t release_id[65];
  uint32_t release_id_len;
  uint8_t manifest_digest[65];
  uint32_t manifest_digest_len;
  uint8_t trust_profile_digest[65];
  uint32_t trust_profile_digest_len;
  uint8_t request_fingerprint[65];
  uint32_t request_fingerprint_len;
  uint8_t transport_descriptor_digest[65];
  uint32_t transport_descriptor_digest_len;
  uint8_t os_transfer_id[257];
  uint32_t os_transfer_id_len;
  uint64_t expected_total_bytes;
  uint32_t platform_code;
  uint32_t android_job_id;
  uint8_t has_android_job_id;
  uint32_t state_code;
  uint64_t prepared_process_generation;
  uint64_t submitted_process_generation;
  uint8_t has_submitted_process_generation;
  uint64_t adopted_process_generation;
  uint8_t has_adopted_process_generation;
} ObMobileRegistryTransferSchedule;

typedef struct ObMobileRegistryLandingProgress {
  uint32_t status_code;
  uint8_t transfer_nonce[129];
  uint32_t transfer_nonce_len;
  uint32_t total_chunks;
  uint32_t verified_chunks;
  uint64_t expected_bytes;
  uint64_t verified_bytes;
  uint8_t bytes_complete;
} ObMobileRegistryLandingProgress;

typedef struct ObMobileRegistryChunkWriteReceipt {
  uint32_t status_code;
  uint8_t transfer_nonce[129];
  uint32_t transfer_nonce_len;
  uint8_t release_id[65];
  uint32_t release_id_len;
  uint32_t artifact_role;
  uint32_t chunk_index;
  uint64_t expected_bytes;
  uint64_t written_bytes;
  uint64_t durable_bytes;
  uint32_t state_code;
} ObMobileRegistryChunkWriteReceipt;

typedef struct ObMobileRuntimeSnapshot {
  uint32_t status_code;
  uint64_t process_generation;
  uint32_t activation_phase;
  uint32_t active_grant_count;
  uint8_t recovered_unclean_start;
  uint8_t bootstrap_store_opened;
  uint8_t registry_bootstrap_only;
  uint8_t local_kql_fixture_verified;
  uint8_t private_planner_verified;
  uint8_t no_llm_provider;
  uint8_t stale_callback_rejected;
  uint8_t secure_profile_active;
  uint8_t installation_binding_verified;
  uint8_t installation_created;
  uint8_t security_session_unlocked;
  uint8_t private_vault_ready;
  uint8_t identity_domains_separated;
  uint8_t privacy_defaults_fail_safe;
  uint8_t redacted_history_ready;
  uint64_t encrypted_raw_draft_count;
  uint64_t pending_share_spool_count;
  uint64_t staged_verified_media_count;
  uint32_t onboarding_cursor;
} ObMobileRuntimeSnapshot;

typedef struct ObMobileRawDraftReceipt {
  uint32_t status_code;
  uint8_t draft_ref[39];
  uint32_t draft_ref_len;
  uint8_t content_language[36];
  uint32_t content_language_len;
  uint64_t content_bytes;
  uint64_t saved_at_monotonic_ms;
  uint64_t total_drafts;
} ObMobileRawDraftReceipt;

typedef struct ObMobileShareSpoolSummary {
  uint32_t status_code;
  uint8_t spool_ref[39];
  uint32_t spool_ref_len;
  uint8_t mime_type[64];
  uint32_t mime_type_len;
  uint64_t content_bytes;
  uint64_t received_at_monotonic_ms;
} ObMobileShareSpoolSummary;

typedef struct ObMobileMediaStageReceipt {
  uint32_t status_code;
  uint8_t source_ref[40];
  uint32_t source_ref_len;
  uint8_t media_class[16];
  uint32_t media_class_len;
  uint8_t mime_type[128];
  uint32_t mime_type_len;
  uint64_t content_bytes;
  uint8_t blake3_digest[64];
  uint32_t blake3_digest_len;
} ObMobileMediaStageReceipt;

/**
 * Return the stable native-to-Rust ABI revision.
 */
uint32_t ob_mobile_bridge_abi_version(void);

/**
 * Return a process-lifetime, NUL-terminated Rust bridge version.
 *
 * The caller must not free or mutate this pointer.
 */
const char *ob_mobile_bridge_core_version(void);

/**
 * Report whether explicit Init has requested signed Registry metadata.
 *
 * This fact does not mean a large artifact transfer was scheduled.
 */
uint8_t ob_mobile_bridge_registry_request_issued(void);

/**
 * Resolve and verify signed Registry metadata, then return an exact local
 * capacity plan. This does not submit or transfer any Registry artifact.
 *
 * # Safety
 *
 * Every pointer must reference its declared readable byte length.
 */
struct ObMobileRegistryPlan ob_mobile_runtime_prepare_registry_init_signed(const uint8_t *channel_id,
                                                                           size_t channel_id_len,
                                                                           const uint8_t *trust_profile_cbor,
                                                                           size_t trust_profile_cbor_len,
                                                                           const uint8_t *channel_head_envelope_cbor,
                                                                           size_t channel_head_envelope_cbor_len,
                                                                           const uint8_t *release_envelope_cbor,
                                                                           size_t release_envelope_cbor_len,
                                                                           uint64_t allocation_unit_bytes,
                                                                           uint64_t destination_total_usable_bytes,
                                                                           uint64_t measured_free_bytes);

/**
 * Persist a Limited-mode receipt bound to the exact reviewed manifest.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable UTF-8 byte lengths.
 */
uint32_t ob_mobile_runtime_defer_registry_init_utf8(const uint8_t *operation_id,
                                                    size_t operation_id_len,
                                                    const uint8_t *manifest_digest,
                                                    size_t manifest_digest_len);

/**
 * Recheck native storage facts and bind exact user confirmation in Rust.
 * This admits capacity only; native must prepare the durable barrier before a
 * separately authorized platform scheduler submission.
 *
 * # Safety
 *
 * Every pointer must reference its declared readable byte length.
 */
struct ObMobileRegistryPlan ob_mobile_runtime_confirm_registry_init_signed(const uint8_t *operation_id,
                                                                           size_t operation_id_len,
                                                                           const uint8_t *manifest_digest,
                                                                           size_t manifest_digest_len,
                                                                           const uint8_t *trust_profile_cbor,
                                                                           size_t trust_profile_cbor_len,
                                                                           uint32_t network_policy_code,
                                                                           uint8_t one_time_network_override,
                                                                           uint64_t allocation_unit_bytes,
                                                                           uint64_t destination_total_usable_bytes,
                                                                           uint64_t measured_free_bytes);

/**
 * Persist the exact pre-scheduler Registry transfer barrier. The request and
 * approved transport descriptor arrive only as already verified digests; no
 * URL, path, credential, or transport handle crosses this ABI.
 *
 * # Safety
 *
 * Every pointer must reference its declared readable UTF-8 byte length.
 */
struct ObMobileRegistryTransferSchedule ob_mobile_runtime_prepare_registry_transfer_schedule_utf8(const uint8_t *operation_id,
                                                                                                  size_t operation_id_len,
                                                                                                  const uint8_t *manifest_digest,
                                                                                                  size_t manifest_digest_len,
                                                                                                  uint32_t platform_code,
                                                                                                  const uint8_t *request_fingerprint,
                                                                                                  size_t request_fingerprint_len,
                                                                                                  const uint8_t *transport_descriptor_digest,
                                                                                                  size_t transport_descriptor_digest_len,
                                                                                                  uint64_t expected_total_bytes,
                                                                                                  uint8_t foreground_user_resume);

/**
 * Record the platform scheduler's durable submit receipt.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable UTF-8 byte lengths.
 */
struct ObMobileRegistryTransferSchedule ob_mobile_runtime_mark_registry_transfer_submitted_utf8(const uint8_t *transfer_nonce,
                                                                                                size_t transfer_nonce_len,
                                                                                                const uint8_t *os_transfer_id,
                                                                                                size_t os_transfer_id_len);

/**
 * Adopt exactly one enumerated platform task after any submit crash window.
 *
 * # Safety
 *
 * Every pointer must reference its declared readable UTF-8 byte length.
 */
struct ObMobileRegistryTransferSchedule ob_mobile_runtime_adopt_registry_transfer_utf8(const uint8_t *transfer_nonce,
                                                                                       size_t transfer_nonce_len,
                                                                                       const uint8_t *os_transfer_id,
                                                                                       size_t os_transfer_id_len,
                                                                                       const uint8_t *observed_request_fingerprint,
                                                                                       size_t observed_request_fingerprint_len,
                                                                                       uint32_t observed_android_job_id,
                                                                                       uint8_t has_observed_android_job_id,
                                                                                       uint32_t matching_task_count);

/**
 * Reconcile an incomplete submitted/adopted transfer whose platform task and
 * terminal landing receipt are both absent.
 *
 * # Safety
 *
 * `transfer_nonce` must reference its declared readable UTF-8 byte length.
 */
struct ObMobileRegistryTransferSchedule ob_mobile_runtime_record_registry_transfer_missing_utf8(const uint8_t *transfer_nonce,
                                                                                                size_t transfer_nonce_len,
                                                                                                uint8_t positive_user_stop_evidence);

/**
 * Resolve the channel's one durable active Registry transfer for native
 * scheduler reconciliation. No platform path or transport descriptor bytes
 * cross this ABI.
 *
 * # Safety
 *
 * `channel_id` must reference its declared readable UTF-8 byte length.
 */
struct ObMobileRegistryTransferSchedule ob_mobile_runtime_registry_transfer_schedule_for_channel_utf8(const uint8_t *channel_id,
                                                                                                      size_t channel_id_len);

/**
 * Materialize the exact signed-manifest-derived chunk ledger for one adopted
 * transfer. No caller-authored hash, length, URL, path, or transport handle is
 * accepted.
 *
 * # Safety
 *
 * `transfer_nonce` must reference its declared readable UTF-8 byte length.
 */
struct ObMobileRegistryLandingProgress ob_mobile_runtime_prepare_registry_chunk_ledger_utf8(const uint8_t *transfer_nonce,
                                                                                            size_t transfer_nonce_len);

/**
 * Reconcile partial/verified chunk files after process death and return the
 * durable typed progress snapshot.
 *
 * # Safety
 *
 * `transfer_nonce` must reference its declared readable UTF-8 byte length.
 */
struct ObMobileRegistryLandingProgress ob_mobile_runtime_recover_registry_chunk_ledger_utf8(const uint8_t *transfer_nonce,
                                                                                            size_t transfer_nonce_len);

/**
 * Query the authoritative verified-byte progress without opening a write
 * session.
 *
 * # Safety
 *
 * `transfer_nonce` must reference its declared readable UTF-8 byte length.
 */
struct ObMobileRegistryLandingProgress ob_mobile_runtime_registry_landing_progress_utf8(const uint8_t *transfer_nonce,
                                                                                        size_t transfer_nonce_len);

/**
 * Open the process-wide native-only write session for one exact signed chunk.
 * The source offset must equal the partial length Rust rehashed from disk.
 *
 * # Safety
 *
 * `transfer_nonce` must reference its declared readable UTF-8 byte length.
 */
struct ObMobileRegistryChunkWriteReceipt ob_mobile_runtime_begin_registry_chunk_write_utf8(const uint8_t *transfer_nonce,
                                                                                           size_t transfer_nonce_len,
                                                                                           uint32_t artifact_role,
                                                                                           uint32_t chunk_index,
                                                                                           uint64_t source_offset);

/**
 * Append one bounded native block. At most one exact Registry chunk session
 * exists in the process, so a callback cannot switch chunk identity between
 * blocks.
 *
 * # Safety
 *
 * `block` must reference its declared readable byte length.
 */
struct ObMobileRegistryChunkWriteReceipt ob_mobile_runtime_append_registry_chunk_write(const uint8_t *block,
                                                                                       size_t block_len);

/**
 * Force a durability checkpoint while keeping the exact session open.
 */
struct ObMobileRegistryChunkWriteReceipt ob_mobile_runtime_checkpoint_registry_chunk_write(void);

/**
 * Verify exact length/hash, fsync, same-volume rename and atomically advance
 * the Rust chunk/operation ledger.
 */
struct ObMobileRegistryChunkWriteReceipt ob_mobile_runtime_finish_registry_chunk_write(void);

/**
 * Checkpoint and close the in-process session while preserving resumable
 * partial bytes for the next process/OS grant.
 */
struct ObMobileRegistryChunkWriteReceipt ob_mobile_runtime_suspend_registry_chunk_write(void);

/**
 * Bounded deterministic call used to verify the complete generated call path.
 */
uint64_t ob_mobile_bridge_round_trip(uint64_t nonce);

/**
 * Open the process-wide mobile runtime from a native-owned UTF-8 data root.
 *
 * Repeated calls in the same process return the existing generation.
 *
 * # Safety
 *
 * `path` must reference `path_len` readable bytes for the duration of this
 * call. The bytes must form a non-empty UTF-8 path.
 */
struct ObMobileRuntimeSnapshot ob_mobile_runtime_open_utf8(const uint8_t *path, size_t path_len);

/**
 * Open the process-wide runtime with native-protected installation material.
 *
 * The native caller must zeroize its temporary plaintext buffer immediately
 * after this function returns. The material never crosses the Dart bridge.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths for the
 * duration of this call.
 */
struct ObMobileRuntimeSnapshot ob_mobile_runtime_open_secure_utf8(const uint8_t *path,
                                                                  size_t path_len,
                                                                  const uint8_t *security_material,
                                                                  size_t security_material_len);

/**
 * Inspect the process-wide runtime without reopening its database.
 */
struct ObMobileRuntimeSnapshot ob_mobile_runtime_snapshot(void);

/**
 * Quiesce the current process generation.
 */
uint32_t ob_mobile_runtime_graceful_stop(void);

/**
 * Lock and zeroize the current private-node session without relying on a
 * lifecycle callback for correctness.
 */
uint32_t ob_mobile_runtime_lock_private_node(void);

/**
 * Persist bounded UTF-8 text as an encrypted `PrivateLocal` raw draft.
 *
 * The returned reference is opaque. No filesystem path, database handle,
 * encryption key or plaintext content is returned.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths for the
 * duration of this call.
 */
struct ObMobileRawDraftReceipt ob_mobile_runtime_save_raw_text_draft_utf8(const uint8_t *content_language,
                                                                          size_t content_language_len,
                                                                          const uint8_t *content_utf8,
                                                                          size_t content_len);

/**
 * Land a bounded native share callback into the encrypted private spool.
 *
 * This native-only entry point is not exposed to Dart. The callback token is
 * used solely for idempotency and the returned spool reference is opaque.
 *
 * # Safety
 *
 * Every pointer must reference its declared readable byte length.
 */
struct ObMobileShareSpoolSummary ob_mobile_runtime_enqueue_shared_text_utf8(const uint8_t *callback_token,
                                                                            size_t callback_token_len,
                                                                            const uint8_t *mime_type,
                                                                            size_t mime_type_len,
                                                                            const uint8_t *content_utf8,
                                                                            size_t content_len);

/**
 * Return one pending encrypted share spool by stable sorted index.
 */
struct ObMobileShareSpoolSummary ob_mobile_runtime_pending_share_spool_at(size_t index);

/**
 * Import a pending `text/plain` spool into an encrypted raw draft.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths.
 */
struct ObMobileRawDraftReceipt ob_mobile_runtime_import_shared_text_utf8(const uint8_t *spool_ref,
                                                                         size_t spool_ref_len,
                                                                         const uint8_t *content_language,
                                                                         size_t content_language_len);

/**
 * Begin a native-owned system-picker stream into encrypted private staging.
 *
 * Neither a provider URI nor filesystem path enters this ABI.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths.
 */
struct ObMobileMediaStageReceipt ob_mobile_runtime_start_media_stage_utf8(const uint8_t *requested_class,
                                                                          size_t requested_class_len,
                                                                          const uint8_t *declared_mime_type,
                                                                          size_t declared_mime_type_len);

/**
 * Append one bounded plaintext chunk; Rust encrypts and commits it before return.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths.
 */
uint32_t ob_mobile_runtime_append_media_stage(const uint8_t *source_ref,
                                              size_t source_ref_len,
                                              const uint8_t *chunk,
                                              size_t chunk_len);

/**
 * Verify the complete encrypted stream and return its opaque source receipt.
 *
 * # Safety
 *
 * `source_ref` must reference its declared readable byte length.
 */
struct ObMobileMediaStageReceipt ob_mobile_runtime_finish_media_stage_utf8(const uint8_t *source_ref,
                                                                           size_t source_ref_len);

/**
 * Mark a non-verified stream interrupted and remove its encrypted partial file.
 *
 * # Safety
 *
 * `source_ref` must reference its declared readable byte length.
 */
uint32_t ob_mobile_runtime_abort_media_stage_utf8(const uint8_t *source_ref, size_t source_ref_len);

/**
 * Persist a bounded onboarding resume cursor in the Rust bootstrap store.
 */
uint32_t ob_mobile_runtime_set_onboarding_cursor(uint32_t cursor_code);

#endif  /* ONEBRAIN_MOBILE_BRIDGE_H */

/* End generated OneBrain Mobile bridge declarations. */
