/*
 * Generated by cbindgen from onebrain-mobile-bridge.
 * Do not edit this file by hand.
 */


#ifndef ONEBRAIN_MOBILE_BRIDGE_H
#define ONEBRAIN_MOBILE_BRIDGE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Stable ABI revision understood by the current Swift/Kotlin adapters.
 */
#define OB_MOBILE_BRIDGE_ABI_VERSION 3

#define OB_MOBILE_RUNTIME_OK 0

#define OB_MOBILE_RUNTIME_INVALID_PATH 1

#define OB_MOBILE_RUNTIME_CORE_ERROR 2

#define OB_MOBILE_RUNTIME_LOCK_POISONED 3

#define OB_MOBILE_RUNTIME_NOT_OPEN 4

#define OB_MOBILE_RUNTIME_INVALID_SECURITY_MATERIAL 5

typedef struct ObMobileRuntimeSnapshot {
  uint32_t status_code;
  uint64_t process_generation;
  uint32_t activation_phase;
  uint32_t active_grant_count;
  uint8_t recovered_unclean_start;
  uint8_t bootstrap_store_opened;
  uint8_t registry_bootstrap_only;
  uint8_t local_kql_fixture_verified;
  uint8_t private_planner_verified;
  uint8_t no_llm_provider;
  uint8_t stale_callback_rejected;
  uint8_t secure_profile_active;
  uint8_t installation_binding_verified;
  uint8_t installation_created;
  uint8_t security_session_unlocked;
  uint8_t private_vault_ready;
  uint8_t identity_domains_separated;
  uint8_t privacy_defaults_fail_safe;
  uint8_t redacted_history_ready;
} ObMobileRuntimeSnapshot;

/**
 * Return the stable native-to-Rust ABI revision.
 */
uint32_t ob_mobile_bridge_abi_version(void);

/**
 * Return a process-lifetime, NUL-terminated Rust bridge version.
 *
 * The caller must not free or mutate this pointer.
 */
const char *ob_mobile_bridge_core_version(void);

/**
 * Report whether this bootstrap-only bridge has requested Registry bytes.
 *
 * Registry transfer authority remains disabled until the explicit Init slice.
 */
uint8_t ob_mobile_bridge_registry_request_issued(void);

/**
 * Bounded deterministic call used to verify the complete generated call path.
 */
uint64_t ob_mobile_bridge_round_trip(uint64_t nonce);

/**
 * Open the process-wide mobile runtime from a native-owned UTF-8 data root.
 *
 * Repeated calls in the same process return the existing generation.
 *
 * # Safety
 *
 * `path` must reference `path_len` readable bytes for the duration of this
 * call. The bytes must form a non-empty UTF-8 path.
 */
struct ObMobileRuntimeSnapshot ob_mobile_runtime_open_utf8(const uint8_t *path, size_t path_len);

/**
 * Open the process-wide runtime with native-protected installation material.
 *
 * The native caller must zeroize its temporary plaintext buffer immediately
 * after this function returns. The material never crosses the Dart bridge.
 *
 * # Safety
 *
 * Both pointers must reference their declared readable byte lengths for the
 * duration of this call.
 */
struct ObMobileRuntimeSnapshot ob_mobile_runtime_open_secure_utf8(const uint8_t *path,
                                                                  size_t path_len,
                                                                  const uint8_t *security_material,
                                                                  size_t security_material_len);

/**
 * Inspect the process-wide runtime without reopening its database.
 */
struct ObMobileRuntimeSnapshot ob_mobile_runtime_snapshot(void);

/**
 * Quiesce the current process generation.
 */
uint32_t ob_mobile_runtime_graceful_stop(void);

/**
 * Lock and zeroize the current private-node session without relying on a
 * lifecycle callback for correctness.
 */
uint32_t ob_mobile_runtime_lock_private_node(void);

#endif  /* ONEBRAIN_MOBILE_BRIDGE_H */

/* End generated OneBrain Mobile bridge declarations. */
