use std::{env, fmt::Write as _, fs, path::Path, path::PathBuf, process::Command};

const GENERATED_HEADER: &str =
    "// Generated from src/test-vectors/vnext/base-v1-runtime-interface-v1.json; DO NOT EDIT.";

fn main() {
    println!("cargo:rerun-if-changed=../test-vectors/vnext/base-v1-runtime-interface-v1.json");
    println!(
        "cargo:rerun-if-changed=../test-vectors/vnext/base-v1-runtime-interface-history-v1.json"
    );
    println!("cargo:rerun-if-changed=../../scripts/base/generate_contract.py");
    println!("cargo:rerun-if-env-changed=ONEBRAIN_BASE_COMMIT");
    println!("cargo:rerun-if-env-changed=ONEBRAIN_TOOLCHAIN_DIGEST");

    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let generated = manifest_dir.join("src/generated.rs");
    let source = fs::read_to_string(&generated).unwrap_or_else(|error| {
        panic!(
            "missing generated Base contract at {}: {error}; run scripts/base/generate_contract.py",
            generated.display()
        )
    });
    if source.lines().next() != Some(GENERATED_HEADER) {
        panic!(
            "generated Base contract provenance drift at {}; run the generator",
            generated.display()
        );
    }

    let target = env::var("TARGET").expect("Cargo target triple");
    assert!(
        !target.is_empty() && target.is_ascii() && target.len() <= 96,
        "Cargo supplied an invalid target triple"
    );
    let commit = env::var("ONEBRAIN_BASE_COMMIT")
        .ok()
        .and_then(|value| verified_commit(&manifest_dir, &value));
    let toolchain = env::var("ONEBRAIN_TOOLCHAIN_DIGEST")
        .ok()
        .and_then(|value| parse_hex::<32>(&value));

    let mut identity = String::new();
    identity.push_str("// Generated by onebrain-base-contract/build.rs; DO NOT EDIT.\n");
    identity.push_str("pub const COMPILED_BASE_COMMIT: SourceCommitIdentity = ");
    match commit {
        Some(VerifiedCommit::Sha1(bytes)) => {
            write!(
                identity,
                "SourceCommitIdentity::Known(SourceCommitId::Sha1(SourceCommitSha1({})))",
                array_literal(&bytes)
            )
            .expect("write identity source");
        }
        Some(VerifiedCommit::Sha256(bytes)) => {
            write!(
                identity,
                "SourceCommitIdentity::Known(SourceCommitId::Sha256(SourceCommitSha256({})))",
                array_literal(&bytes)
            )
            .expect("write identity source");
        }
        None => identity.push_str("SourceCommitIdentity::Unknown"),
    }
    identity.push_str(";\n");
    identity.push_str("pub const COMPILED_TOOLCHAIN: ToolchainIdentity = ");
    match toolchain {
        Some(bytes) => write!(
            identity,
            "ToolchainIdentity::Known(ToolchainDigest({}))",
            array_literal(&bytes)
        )
        .expect("write toolchain source"),
        None => identity.push_str("ToolchainIdentity::Unknown"),
    }
    identity.push_str(";\n");
    writeln!(
        identity,
        "pub const COMPILED_TARGET_TRIPLE: &str = {:?};",
        target
    )
    .expect("write target source");
    fs::write(
        PathBuf::from(env::var_os("OUT_DIR").expect("Cargo OUT_DIR"))
            .join("base_build_identity.rs"),
        identity,
    )
    .expect("write Base build identity");
}

enum VerifiedCommit {
    Sha1([u8; 20]),
    Sha256([u8; 32]),
}

fn verified_commit(manifest_dir: &Path, value: &str) -> Option<VerifiedCommit> {
    let parsed = match value.len() {
        40 => VerifiedCommit::Sha1(parse_hex(value)?),
        64 => VerifiedCommit::Sha256(parse_hex(value)?),
        _ => return None,
    };
    let status = Command::new("git")
        .arg("-C")
        .arg(manifest_dir)
        .arg("cat-file")
        .arg("-e")
        .arg(format!("{value}^{{commit}}"))
        .status()
        .ok()?;
    status.success().then_some(parsed)
}

fn parse_hex<const N: usize>(value: &str) -> Option<[u8; N]> {
    if value.len() != N * 2
        || !value
            .as_bytes()
            .iter()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(byte))
    {
        return None;
    }
    let mut output = [0; N];
    for (index, slot) in output.iter_mut().enumerate() {
        *slot = u8::from_str_radix(&value[index * 2..index * 2 + 2], 16).ok()?;
    }
    Some(output)
}

fn array_literal<const N: usize>(bytes: &[u8; N]) -> String {
    let body = bytes
        .iter()
        .map(u8::to_string)
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{body}]")
}
